### ISSUE TITLE
uWSGI - compilation error on Windows

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-flask-best-practices#3]
The modules Installation fails on Windows for uWSGI (see the error log). 

Patch: Replace `uWSGI` with `Gunicorn`

**err log**

```log
Collecting uwsgi
  Downloading uwsgi-2.0.20.tar.gz (804 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 804.9/804.9 KB 5.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Sm0ke\AppData\Local\Temp\pip-install-umluqnaj\uwsgi_9b6e155339de40caa380227bbf6e1840\setup.py", line 3, in <module>
          import uwsgiconfig as uc
        File "C:\Users\Sm0ke\AppData\Local\Temp\pip-install-umluqnaj\uwsgi_9b6e155339de40caa380227bbf6e1840\uwsgiconfig.py", line 8, in <module>
          uwsgi_os = os.uname()[0]
      AttributeError: module 'os' has no attribute 'uname'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by app-generator** [comment]
Closing
