### ISSUE TITLE
Runtime Errors - @security[talisman] / SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-flask-best-practices#5]
During the runtime, the app crashes with `SyntaxError: invalid syntax`  caused by the version of Python (3.9 or greater required). 

Would be great to support the usage of the App for earlier versions of Python, starting with `3.6.0`. 
Sometimes, the deployment servers use old versions. 

 **Error Log**

```log
(env) PS D:\work\repo-samples\sample-flask-best-practices> flask run
 * Serving Flask app 'run.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\work\repo-samples\sample-flask-best-practices\env\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\flask\cli.py", line 985, in main
    cli.main()
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\flask\cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\flask\cli.py", line 847, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\flask\cli.py", line 299, in __init__
    self._load_unlocked()
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\flask\cli.py", line 333, in _load_unlocked
    self._app = rv = self.loader()
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\flask\cli.py", line 389, in load_app
    app = locate_app(import_name, name)
  File "D:\work\repo-samples\sample-flask-best-practices\env\lib\site-packages\flask\cli.py", line 234, in locate_app
    __import__(module_name)
  File "D:\work\repo-samples\sample-flask-best-practices\run.py", line 4, in <module>
    app = create_app(config_name='development')
  File "D:\work\repo-samples\sample-flask-best-practices\app\__init__.py", line 58, in create_app
    from app.auth.routes import auth
  File "D:\work\repo-samples\sample-flask-best-practices\app\auth\routes.py", line 24
    @security["talisman"](frame_options=ALLOW_FROM,
             ^
SyntaxError: invalid syntax
```

**Comment by raviwrk-official** [comment]
working on the same

**Comment by app-generator** [comment]
Closing. We can use Py.10
